#!/bin/bash

#SBATCH --job-name=runFoam-V1.12
#SBATCH --partition=64c512g
#SBATCH -n 64
#SBATCH --ntasks-per-node=64
#SBATCH --output=%j.out
#SBATCH --error=%j.err

#1. Defining the container to be used
theRepo=/dssg/home/acct-medgm/medgm/00-sif
theContainerBaseName=openfoam
theVersion=v2006
theProvider=wjq
theImage=$theRepo/$theContainerBaseName-$theVersion-$theProvider.sif
 
#2. Project Name
project_name=03-hisa
foam_numberOfSubdomains=64

#2. Control parameter
theSolver=hisa
foam_MachInlet="1.12"     
foam_MacsOutlet="0.7"
foam_polyMesh_type="short"
foam_writeFormat="binary"
foam_fluxSchemes="AUSMPlusUp"

#2. Steady parameter
foam_steady_writeInterval="5000"
foam_steady_maxCo="1.0e20"
foam_steady_endTime="5000"
foam_steady_deltaT="1"
foam_steady_ddtScheme="steadyState"
foam_steady_writeControl="timeStep"
foam_steady_startFrom="startTime"
foam_steady_purgeWrite="0"
foam_steady_numberOfSubdomains=$foam_numberOfSubdomains
foam_steady_writeFormat=$foam_writeFormat
foam_steady_runTimeModifiable="false"
foam_steady_fluxSchemes=$foam_fluxSchemes
foam_steady_polyMesh_type=$foam_polyMesh_type
foam_steady_MachInlet=$foam_MachInlet
foam_steady_MacsOutlet=$foam_MacsOutlet

# Relax first to speed up
# zeroGradient boundary
#2. Transient1 parameter
foam_transient1_writeInterval="0.0001"
foam_transient1_maxCo="45" 
foam_transient1_endTime="0.0001" 
foam_transient1_deltaT="5.0e-7"
foam_transient1_ddtScheme="backward" 
foam_transient1_writeControl="adjustableRunTime"  
foam_transient1_runTimeModifiable="true"
foam_transient1_startFrom="latestTime"
foam_transient1_purgeWrite="0"
foam_transient1_numberOfSubdomains=$foam_numberOfSubdomains
foam_transient1_writeFormat=$foam_writeFormat
foam_transient1_fluxSchemes=$foam_fluxSchemes
foam_transient1_polyMesh_type=$foam_polyMesh_type
foam_transient1_MachInlet=$foam__MachInlet
foam_transient1_MacsOutlet=$foam__MacsOutlet

# Need to choose boundary condition
#2. Transient2 parameter
foam_transient2_writeInterval="1e-6"
foam_transient2_maxCo="20"
foam_transient2_endTime="0.01"
foam_transient2_deltaT="5.0e-7"
foam_transient2_ddtScheme="backward"
foam_transient2_writeControl="adjustableRunTime"
foam_transient2_runTimeModifiable="true"
foam_transient2_startFrom="latestTime"
foam_transient2_purgeWrite="0"
foam_transient2_numberOfSubdomains=$foam_numberOfSubdomains
foam_transient2_writeFormat=$foam_writeFormat
foam_transient2_fluxSchemes=$foam_fluxSchemes
foam_transient2_polyMesh_type=$foam_polyMesh_type
foam_transient2_MachInlet=$foam__MachInlet
foam_transient2_MacsOutlet=$foam__MacsOutlet

# Select boundary condition 
#1-ofBasic1,2-ofBasic2,3-charac,4-NRBC,5-fixValue
foam_transient2_pInletBoundary=3
foam_transient2_TInletBoundary=3
foam_transient2_UInletBoundary=3
foam_transient2_pOutletBoundary=4
foam_transient2_TOutletBoundary=4
foam_transient2_UOutletBoundary=4

#2. Project Name
caseName=S03-$theSolver-$foam_MachInlet-$foam_MacsOutlet-$foam_fluxSchemes-$foam_steady_endTime-maxCo$foam_transient1_maxCo-$foam_transient1_deltaT-$foam_polyMesh_type-$foam_transient2_pInletBoundary$foam_transient2_TInletBoundary$foam_transient2_UInletBoundary$foam_transient2_pOutletBoundary$foam_transient2_TOutletBoundary$foam_transient2_UOutletBoundary


polyMeshName=polyMesh-igg-final-$foam_polyMesh_type


projectUserDir=$SLURM_SUBMIT_DIR/../../projectUserDir
baseWorkingDir=$SLURM_SUBMIT_DIR/../../run
caseDir=$baseWorkingDir/$caseName
logsDir=$caseDir/logs/pre



#4. Copy the file to run
mkdir -p $baseWorkingDir
#rm -rf $baseWorkingDir/$caseName
cp -rf $SLURM_SUBMIT_DIR/../../test_cases/$project_name  $caseDir

# create log directory
if ! [ -d $logsDir ]; then
   mkdir -p $logsDir
fi


#5. Defining OpenFOAM controlDict settings for Pawsey Best Practices
echo "----------> cd to $caseDir"
cd $caseDir
rm -rf *.err
rm -rf *.out
rm -rf constant/polyMesh
cp -rf constant/$polyMeshName constant/polyMesh
rm -rf constant/polyMesh-igg*
rm -rf constant/igg*

echo "----------> restore0Dir"
mv 0_org 0
if [ $foam_polyMesh_type == "short-3d" ]
then
     echo "change empty to cyclicAMI"
     grep -l -r 'empty' 0| xargs sed -i 's,empty,cyclicAMI,g'
fi


#5. steday controlDict Setting
sed -i 's,^writeFormat.*,writeFormat    '"$foam_steady_writeFormat"';,' ./system/controlDict
sed -i 's,^runTimeModifiable.*,runTimeModifiable    '"$foam_steady_runTimeModifiable"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_steady_purgeWrite"';,' ./system/controlDict
sed -i 's,^startFrom.*,startFrom    '"$foam_steady_startFrom"';,' ./system/controlDict
sed -i 's,^deltaT.*,deltaT    '"$foam_steady_deltaT"';,' ./system/controlDict
sed -i 's,^writeInterval.*,writeInterval    '"$foam_steady_writeInterval"';,' ./system/controlDict
sed -i 's,^writeControl.*,writeControl    '"$foam_steady_writeControl"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_steady_purgeWrite"';,' ./system/controlDict
sed -i 's,^maxCo.*,maxCo    '"$foam_steady_maxCo"';,' ./system/controlDict
sed -i 's,^endTime.*,endTime    '"$foam_steady_endTime"';,' ./system/controlDict
sed -i 's,^numberOfSubdomains.*,numberOfSubdomains    '"$foam_steady_numberOfSubdomains"';,' ./system/decomposeParDict
sed -i 's,^Mach.*,Mach    '"$foam_steady_MachInlet"';,' ./0/include/freestreamConditions
sed -i 's,^Macs.*,Macs    '"$foam_steady_MacsOutlet"';,' ./0/include/freestreamConditions
sed -i 's,^fluxScheme.*,fluxScheme    '"$foam_steady_fluxSchemes"';,' ./system/fvSchemes
sed -i 's,backward,'"$foam_steady_ddtScheme"','  ./system/fvSchemes


echo "----------> Decompose"
singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage decomposePar -force 2>&1 | tee $logsDir/log.decomposePar2.$SLURM_JOBID

echo "----------> run the $theSolver"
srun --mpi=pmi2 singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage $theSolver -parallel 2>&1 | tee $logsDir/log.steadytheSolver.$SLURM_JOBID

echo "----------> FINISH STEADY STEP"

echo "----------> Reconstruct latest result"
singularity run -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage reconstructPar  2>&1 | tee $logsDir/log.reconstructPar.$SLURM_JOBID


rm -rf processors$foam_numberOfSubdomains
cp -rf 0/include $foam_steady_endTime
rm -rf 0
mv $foam_steady_endTime 0
rm -rf 0/uniform
sed -i '/location/d' 0/*
mv postProcessing oldpostProcessing 


#5. Transient controlDict Setting
sed -i 's,^writeFormat.*,writeFormat    '"$foam_transient1_writeFormat"';,' ./system/controlDict
sed -i 's,^runTimeModifiable.*,runTimeModifiable    '"$foam_transient1_runTimeModifiable"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_transient1_purgeWrite"';,' ./system/controlDict
sed -i 's,^startFrom.*,startFrom    '"$foam_transient1_startFrom"';,' ./system/controlDict
sed -i 's,^deltaT.*,deltaT    '"$foam_transient1_deltaT"';,' ./system/controlDict
sed -i 's,^writeInterval.*,writeInterval    '"$foam_transient1_writeInterval"';,' ./system/controlDict
sed -i 's,^writeControl.*,writeControl    '"$foam_transient1_writeControl"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_transient1_purgeWrite"';,' ./system/controlDict
sed -i 's,^maxCo.*,maxCo    '"$foam_transient1_maxCo"';,' ./system/controlDict
sed -i 's,^endTime.*,endTime    '"$foam_transient1_endTime"';,' ./system/controlDict
sed -i 's,^numberOfSubdomains.*,numberOfSubdomains    '"$foam_transient1_numberOfSubdomains"';,' ./system/decomposeParDict
sed -i 's,^fluxScheme.*,fluxScheme    '"$foam_transient1_fluxSchemes"';,' ./system/fvSchemes
sed -i 's,steadyState,'"$foam_transient1_ddtScheme"','  ./system/fvSchemes



echo "----------> Decompose"
singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage decomposePar -force 2>&1 | tee $logsDir/log.decomposePar2.$SLURM_JOBID

echo "----------> run the transient1 $theSolver"
srun --mpi=pmi2 singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage $theSolver -parallel 2>&1 | tee $logsDir/log.trasient1theSolver.$SLURM_JOBID

echo "----------> FINISH TRANSIENT1 STEP"


echo "----------> Reconstruct latest result"
singularity run -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage reconstructPar -time 0:$foam_transient1_endTime 2>&1 | tee $logsDir/log.reconstructPar.$SLURM_JOBID

foam_transient2_startTime=$foam_transient1_endTime

cp -rf 0/include  $foam_transient2_startTime
line=18
insertHead='i\
#include        "include/freestreamConditions"
'
sed -i "$line$insertHead" $foam_transient2_startTime/T
sed -i "$line$insertHead" $foam_transient2_startTime/U
sed -i "$line$insertHead" $foam_transient2_startTime/p


echo "----------> Select Boundary Condition!"
echo "----------> 1-ofBasic1,2-ofBasic2,2-charac,4-NRBC,5-fixValue"
#INLET-Pressure
case $foam_transient2_pInletBoundary in
    1)
        echo "pInlet eroGradient"
insertpinlet='i\
        type         zeroGradient;
'
        ;;	
    2)
        echo "pInlet totalPressure"
insertpinlet='i\
       type            totalPressure; \
       psi             thermo:psi; \
       gamma           1.4; \
       p0              uniform $ptotal;
'    
        ;;
    3)
        echo "pInlet characteristicFarfieldPressure"
insertpinlet='i\
        type         characteristicFarfieldPressure; \
        U            $Uinlet; \
        p            $pinlet; \
        T            $Tinlet; 
'
        ;;
    4)
        echo "pInlet NRBC"
insertpinlet='i\
        type            pressureOutletNSCBC; \
        field           p; \
        gamma           1.4; \
        fieldInf        1; \
        lInf            0.07; \
        pInf            $pinlet; \
        etaAc           1;
'
        ;;
    5)
        echo "pInlet fixValue"
insertpinlet='i\
        type            fixedValue; 
'
        ;;
esac


#OUTLET-pressure
case $foam_transient2_pOutletBoundary in
    1)
        echo "pOutlet fixedMean"
insertpoutlet='i\
        type         fixedMean; \
        meanValue    $poutlet; 
'
        ;;
    2)
        echo "pOutlet waveTransmissive"
insertpoutlet='i\
        type            waveTransmissive; \
        field           p; \
        psi             thermo:psi; \
        gamma           1.4; \
        fieldInf        $poutlet; \
        lInf            1e-5;        
'
        ;;
    3)
        echo "pOutlet characteristicFarfieldPressure"
insertpoutlet='i\
        type         characteristicFarfieldPressure; \
        U            $Uoutlet; \
        p            $poutlet; \
        T            $Toutlet;
'
        ;;
    4)
        echo "pOutlet NRBC"
insertpoutlet='i\
        type            pressureOutletNSCBC; \
        field           p; \
        gamma           1.4; \
        fieldInf        1; \
        lInf            0.07; \
        pInf            $poutlet; \
        etaAc           1; 
'
        ;;
    5)
        echo "pOutlet fixValue"
insertpoutlet='i\
        type            fixedValue; 
'
        ;;
esac





#INLET-Temperature
case $foam_transient2_TInletBoundary in
    1)
        echo "pOutlet zeroGradient"
insertTinlet='i\
	type         zeroGradient; 
'
        ;;
    2)
        echo "pOutlet totalTemperature"
insertTinlet='i\
       type            totalTemperature; \
       psi             thermo:psi; \
       gamma           1.4; \
       T0              uniform $Ttotal; 
'
        ;;
    3)
        echo "pOutlet characteristicFarfieldTemperature"
insertTinlet='i\
        type         characteristicFarfieldTemperature; \
        U            $Uinlet; \
        p            $pinlet; \
        T            $Tinlet; 
'
        ;;
    4)
        echo "pOutlet NRBC"
insertTinlet='i\
	type            temperatureOutletNSCBC; \
        field           T; \
        gamma           1.4; \
        fieldInf        1; \
        lInf            0.07; \
        pInf            $pinlet; \
        etaAc           1; 
'
        ;;
    5)
        echo "pOutlet fixValue"
insertTinlet='i\
        type            fixedValue; 
'
        ;;
esac






#OUTLET-Temperature
case $foam_transient2_TOutletBoundary in
    1)
        echo "TOutlet zeroGradient"
insertToutlet='i\
        type         zeroGradient; 
'
        ;;
    2)
        echo "TOutlet waveTransmissive"
insertToutlet='i\
        type            waveTransmissive; \
        field           T; \
        psi             thermo:psi; \
        gamma           1.4; \
        fieldInf        $Toutlet; \
        lInf            1e-5;      
'
        ;;
    3)
        echo "TOutlet characteristicFarfieldTemperature"
insertToutlet='i\
        type         characteristicFarfieldTemperature; \
        U            $Uoutlet; \
        p            $poutlet; \
        T            $Toutlet;
'
        ;;
    4)
        echo "TOutlet NRBC"
insertToutlet='i\
        type            temperatureOutletNSCBC; \
        field           T; \
        gamma           1.4; \
        fieldInf        1; \
        lInf            0.07; \
        pInf            $poutlet; \
        etaAc           1; 
'
        ;;
    5)
        echo "TOutlet fixValue"
insertToutlet='i\
        type            fixedValue; 
'
        ;;
esac





#INLET-Velocity
case $foam_transient2_UInletBoundary in
    1)
        echo "UInlet freestreamVelocity"
insertUinlet='i\
        type            freestreamVelocity; \
        freestreamValue uniform $Uinlet; 
'
        ;;
    2)
        echo "UInlet EMPTY"
        ;;
    3)
        echo "UInlet characteristicFarfieldVelocity"
insertUinlet='i\
        type         characteristicFarfieldVelocity; \
        U            $Uinlet; \
        p            $pinlet; \
        T            $Tinlet; 
'
        ;;
    4)
        echo "UInlet velocityOutletNSCBCx"
insertUinlet='i\
        type            velocityOutletNSCBCx; \
        pInf            $pinlet; \
        gamma           1.4; \
        etaAc           1; \
        fieldInf        (-1 0 0); \
        lInf            0.07; 
'
        ;;
    5)
        echo "UInlet fixValue"
insertUinlet='i\
        type            fixedValue; 
'
esac






#OUTLET-Velocity
case $foam_transient2_UOutletBoundary in
    1)
        echo "UOutlet zeroGradient"
insertUoutlet='i\
	type zeroGradient;
'
        ;;
    2)
        echo "UOutlet inletOutlet"
insertUoutlet='i\
        type            inletOutlet; \
        inletValue      uniform $Uinlet; 
'
        ;;
    3)
        echo "UOutlet characteristicFarfieldVelocity"
insertUoutlet='i\
        type         characteristicFarfieldVelocity; \
        U            $Uoutlet; \
        p            $poutlet; \
        T            $Toutlet; 
'
        ;;
    4)
        echo "UOutlet velocityOutletNSCBCx"
insertUoutlet='i\
        type            velocityOutletNSCBCx; \
        pInf            $poutlet; \
        gamma           1.4; \
        etaAc           1; \
        fieldInf        (1 0 0); \
        lInf            0.07; 
'
        ;;
    5)
        echo "UOutlet fixValue"
insertUoutlet='i\
        type            fixedValue; 
'
        ;;
esac






function getOutletLineT() {
        sed -n -e '/OUTLET/=' $foam_transient2_startTime/T
}
function getOutletLineU() {
        sed -n -e '/OUTLET/=' $foam_transient2_startTime/U
}
function getOutletLinep() {
        sed -n -e '/OUTLET/=' $foam_transient2_startTime/p
}


function getInletLineT() {
        sed -n -e '/INLET/=' $foam_transient2_startTime/T
}
function getInletLineU() {
        sed -n -e '/INLET/=' $foam_transient2_startTime/U
}
function getInletLinep() {
        sed -n -e '/INLET/=' $foam_transient2_startTime/p
}


echo "----------> DEBUG"
echo $(getOutletLineT)
echo $(getOutletLineU)
echo $(getOutletLineU)
echo $(getInletLineT)
echo $(getInletLineU)
echo $(getInletLinep)



#ä=/space bug
lineTOutlet=$(getOutletLineT)
lineT1Outlet=$((lineTOutlet+2)) 
lineT2Outlet=$((lineT1Outlet+0)) 
lineUOutlet=$(getOutletLineU)
lineU1Outlet=$((lineUOutlet+2)) 
lineU2Outlet=$((lineU1Outlet+0)) 
linepOutlet=$(getOutletLinep)
linep1Outlet=$((linepOutlet+2))
linep2Outlet=$((linep1Outlet+1)) 


lineTInlet=$(getInletLineT)
lineT1Inlet=$((lineTInlet+2))
lineT2Inlet=$((lineT1Inlet+0)) 
lineUInlet=$(getInletLineU)
lineU1Inlet=$((lineUInlet+2))
lineU2Inlet=$((lineU1Inlet+1)) 
linepInlet=$(getInletLinep)
linep1Inlet=$((linepInlet+2))
linep2Inlet=$((linep1Inlet+0)) 




echo $lineTInlet
echo $lineT1Inlet
echo $lineT2Inlet
echo $lineUInlet
echo $lineU1Inlet
echo $lineU2Inlet
echo $linepInlet
echo $linep1Inlet
echo $linep2Inlet



insert_Outlet_func() {
        sed -i "${lineT1Outlet},${lineT2Outlet}d" $foam_transient2_startTime/T
        sed -i "${lineT1Outlet}${insertToutlet}" $foam_transient2_startTime/T
        sed -i "${lineU1Outlet},${lineU2Outlet}d" $foam_transient2_startTime/U
        sed -i "${lineU1Outlet}${insertUoutlet}" $foam_transient2_startTime/U
        sed -i "${linep1Outlet},${linep2Outlet}d" $foam_transient2_startTime/p
        sed -i "${linep1Outlet}${insertpoutlet}" $foam_transient2_startTime/p
}


insert_Inlet_func() {
        sed -i "${lineT1Inlet},${lineT2Inlet}d" $foam_transient2_startTime/T
        sed -i "${lineT1Inlet}${insertTinlet}" $foam_transient2_startTime/T
        sed -i "${lineU1Inlet},${lineU2Inlet}d" $foam_transient2_startTime/U
        sed -i "${lineU1Inlet}${insertUinlet}" $foam_transient2_startTime/U
        sed -i "${linep1Inlet},${linep2Inlet}d" $foam_transient2_startTime/p
        sed -i "${linep1Inlet}${insertpinlet}" $foam_transient2_startTime/p
}









echo "----------> Insert INLET/OUTLET BOUNDRY"
insert_Outlet_func
insert_Inlet_func

echo "----------> Insert associated controlDict/fvSchemes"

sed -i 's,^writeFormat.*,writeFormat    '"$foam_transient2_writeFormat"';,' ./system/controlDict
sed -i 's,^runTimeModifiable.*,runTimeModifiable    '"$foam_transient2_runTimeModifiable"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_transient2_purgeWrite"';,' ./system/controlDict
sed -i 's,^startFrom.*,startFrom    '"$foam_transient2_startFrom"';,' ./system/controlDict
sed -i 's,^deltaT.*,deltaT    '"$foam_transient2_deltaT"';,' ./system/controlDict
sed -i 's,^writeInterval.*,writeInterval    '"$foam_transient2_writeInterval"';,' ./system/controlDict
sed -i 's,^writeControl.*,writeControl    '"$foam_transient2_writeControl"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_transient2_purgeWrite"';,' ./system/controlDict
sed -i 's,^maxCo.*,maxCo    '"$foam_transient2_maxCo"';,' ./system/controlDict
sed -i 's,^endTime.*,endTime    '"$foam_transient2_endTime"';,' ./system/controlDict
sed -i 's,^numberOfSubdomains.*,numberOfSubdomains    '"$foam_transient2_numberOfSubdomains"';,' ./system/decomposeParDict
sed -i 's,^fluxScheme.*,fluxScheme    '"$foam_transient2_fluxSchemes"';,' ./system/fvSchemes
sed -i 's,steadyState,'"$foam_transient2_ddtScheme"','  ./system/fvSchemes
sed -i 's,dualTime rPseudoDeltaT,,' ./system/fvSchemes 


echo "----------> Decompose"
singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage decomposePar -force -latestTime 2>&1 | tee $logsDir/log.decomposePar2.$SLURM_JOBID


echo "----------> run the transient2 $theSolver"
srun --mpi=pmi2 singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage $theSolver -parallel 2>&1 | tee $logsDir/log.trasient2theSolver.$SLURM_JOBID

echo "----------> Reconstruct latest result"
singularity run -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage reconstructPar -time $foam_transient1_endTime:$foam_transient2_endTime  2>&1 | tee $logsDir/log.reconstructPar.$SLURM_JOBID



echo "----------> PostProcessing xyz for paraview plot"
singularity run -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage postProcess -func writeCellCentres  2>&1 | tee $logsDir/log.postprocessing.$SLURM_JOBID

echo "----------> FINISH"
