/*---------------------------------------------------------------------------*\

    HiSA: High Speed Aerodynamic solver

    Copyright (C) 2014-2018 Johan Heyns - CSIR, South Africa
    Copyright (C) 2014-2018 Oliver Oxtoby - CSIR, South Africa
    Copyright (C) 2011-2012 OpenFOAM Foundation

-------------------------------------------------------------------------------
License
    This file is part of HiSA.

    HiSA is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HiSA is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HiSA.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::characteristicFarfieldTemperatureFvPatchScalarField

Group
    grpInletBoundaryConditions grpOutletBoundaryConditions

Description
    This boundary condition provides a non-reflecting far-field condition.
    See characteristicBase for usage.

SourceFiles
    characteristicFarfieldTemperatureFvPatchScalarField.C

Authors
    Johan Heyns
    Oliver Oxtoby
        Council for Scientific and Industrial Research, South Africa

\*---------------------------------------------------------------------------*/

#ifndef characteristicFarfieldTemperatureFvPatchScalarFields_H
#define characteristicFarfieldTemperatureFvPatchScalarFields_H

#include "fvPatchFields.H"
#include "characteristicBase.H"
#include "mixedFvPatchFields.H"
#include "surfaceFields.H"
#include "characteristicBase.H"
#include "BlockCoupledBoundary.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
           Class characteristicFarfieldTemperatureFvPatchScalarField Declaration
\*---------------------------------------------------------------------------*/

class characteristicFarfieldTemperatureFvPatchScalarField
:
    public mixedFvPatchScalarField,
    public characteristicBase,
    public BlockCoupledBoundary<scalar>
{
protected:

    scalarField TCoeff_;
    vectorField UCoeff_;
    scalarField pCoeff_;

public:

    //- Runtime type information
    TypeName("characteristicFarfieldTemperature");


    // Constructors

        //- Construct from patch and internal field
        characteristicFarfieldTemperatureFvPatchScalarField
        (
            const fvPatch&,
            const DimensionedField<scalar, volMesh>&
        );

        //- Construct from patch, internal field and dictionary
        characteristicFarfieldTemperatureFvPatchScalarField
        (
            const fvPatch&,
            const DimensionedField<scalar, volMesh>&,
            const dictionary&
        );

        //- Construct by mapping given characteristicFarfieldTemperatureFvPatchScalarField
        //  onto a new patch
        characteristicFarfieldTemperatureFvPatchScalarField
        (
            const characteristicFarfieldTemperatureFvPatchScalarField&,
            const fvPatch&,
            const DimensionedField<scalar, volMesh>&,
            const fvPatchFieldMapper&
        );

        //- Construct as copy
        characteristicFarfieldTemperatureFvPatchScalarField
        (
            const characteristicFarfieldTemperatureFvPatchScalarField&
        ) = delete;

#if FOUNDATION >= 9
#else
        //- Construct and return a clone
        virtual tmp<fvPatchScalarField> clone() const override
        {
            return tmp<fvPatchScalarField>
            (
                new characteristicFarfieldTemperatureFvPatchScalarField
                (
                    *this, this->internalField()
                )
            );
        }
#endif

        //- Construct as copy setting internal field reference
        characteristicFarfieldTemperatureFvPatchScalarField
        (
            const characteristicFarfieldTemperatureFvPatchScalarField&,
            const DimensionedField<scalar, volMesh>&
        );

        //- Construct and return a clone setting internal field reference
        virtual tmp<fvPatchScalarField> clone
        (
            const DimensionedField<scalar, volMesh>& iF
        ) const override
        {
            return tmp<fvPatchScalarField>
            (
                new characteristicFarfieldTemperatureFvPatchScalarField(*this, iF)
            );
        }


    // Member functions

        // Mapping functions

            //- Map (and resize as needed) from self given a mapping object
            virtual void autoMap
            (
                const fvPatchFieldMapper&
            ) override;

            //- Reverse map the given fvPatchField onto this fvPatchField
            virtual void rmap
            (
                const fvPatchScalarField&,
                const labelList&
            ) override;

        // Evaluation functions

            //- Update the coefficients associated with the patch field
            virtual void updateCoeffs() override;

        //- Block-coupled boundary coefficients

            virtual tmp<scalarField> valueInternalCoeffs
            (
                const volScalarField& field
            ) const override;

            virtual tmp<scalarField> gradientInternalCoeffs
            (
                const volScalarField& field
            ) const override;

            virtual tmp<vectorField> valueInternalCoeffs
            (
                const volVectorField& field
            ) const override;

            virtual tmp<vectorField> gradientInternalCoeffs
            (
                const volVectorField& field
            ) const override;

        //- Write
        virtual void write(Ostream&) const override;
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
