#!/bin/bash

#~~~~~~~~~~~~~~~~~~~~~#
fluxScheme='rusanov'
limiter="BarthJespersen"
point='400'

caseName=00-$fluxScheme-$limiter-$point

cp -rf 00-basic-400 $caseDir
cd $caseDir

sed -i 's,^flux.*,flux    '"$fluxScheme"';,' ./system/fvSchemes
sed -i 's,^limiter.*,limiter    '"$fluxScheme"';,' ./system/controlDict

bash Allrun

