/*---------------------------------------------------------------------------*\

    HiSA: High Speed Aerodynamic solver

    Copyright (C) 2014-2018 Oliver Oxtoby - CSIR, South Africa
    Copyright (C) 2014-2018 Johan Heyns - CSIR, South Africa

-------------------------------------------------------------------------------
License
    This file is part of HiSA.

    HiSA is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HiSA is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HiSA.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

    const Time& runTime = time_;
    pseudotimeControl& solnControl = solnControl_();
    fvMesh& mesh = mesh_();

    psiThermo& thermo = pThermo_();

    volScalarField& p = thermo.p();
    volScalarField& e = thermo.he();
    volScalarField& T = thermo.T();
    const volScalarField& psi = thermo.psi();

    volVectorField& U = U_();

    volScalarField& rho = scalarVars_[0];
    volVectorField& rhoU = vectorVars_[0];
    volScalarField& rhoE = scalarVars_[1];

    surfaceScalarField& phi = phi_();

    volScalarField& rPseudoDeltaT = rPseudoDeltaT_();
    scalarField& ddtCoeff = ddtCoeff_();

    volScalarField& rhoR = scalarResiduals_[0];
    volVectorField& rhoUR = vectorResiduals_[0];
    volScalarField& rhoER = scalarResiduals_[1];

    fluxScheme& flux = flux_();
