/*---------------------------------------------------------------------------*\

    HiSA: High Speed Aerodynamic solver

    Copyright (C) 2014-2018 Johan Heyns - CSIR, South Africa
    Copyright (C) 2014-2018 Oliver Oxtoby - CSIR, South Africa
    Copyright (C) 2011-2013 OpenFOAM Foundation

-------------------------------------------------------------------------------
License
    This file is part of HiSA.

    HiSA is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HiSA is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HiSA.  If not, see <http://www.gnu.org/licenses/>.


Class
    Foam::preconditioner

Description
    Base class for preconditioners

SourceFiles
    preconditionerNew.C

Authors
    Johan Heyns
    Oliver Oxtoby
        Council for Scientific and Industrial Research, South Africa

\*---------------------------------------------------------------------------*/

#ifndef preconditioner_H
#define preconditioner_H

#include "IOdictionary.H"
#include "volFields.H"
#include "fvCFD.H"
#include "autoPtr.H"
#include "runTimeSelectionTables.H"
#include "jacobianMatrix.H"


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
              Class preconditioner Declaration
\*---------------------------------------------------------------------------*/

template <int nScalar, int nVector>
class preconditioner
{

protected:
    // Protected data

        const jacobianMatrix<nScalar, nVector>& jacobian_;

        const fvMesh& mesh_;

        const preconditioner* prePreconditioner_;

private:
    // Private Member Functions

        //- Disallow copy construct
        preconditioner(const preconditioner&);

        //- Disallow default bitwise assignment
        void operator=(const preconditioner&);

public:
    //- Runtime type information
    TypeName("preconditioner");


    // Declare run-time constructor selection table

        declareRunTimeSelectionTable
        (
            autoPtr,
            preconditioner,
            dictionary,
            (
                const dictionary& dict,
                const jacobianMatrix<nScalar, nVector>& jacobian,
                const preconditioner* prePreconditioner
            ),
            (dict, jacobian, prePreconditioner)
        );


	// Constructors

        //- Construct from components
        preconditioner
        (
            const word& type,
            const dictionary& dict,
            const jacobianMatrix<nScalar, nVector>& jacobian,
            const preconditioner<nScalar, nVector>* prePreconditioner
        )
         :
            jacobian_(jacobian),
            mesh_(jacobian.mesh()),
            prePreconditioner_(prePreconditioner)
        {}


    // Selectors

        //- Return a pointer to the selected preconditioner
        static autoPtr<preconditioner> New
        (
            const dictionary& dict,
            const jacobianMatrix<nScalar, nVector>& jacobian,
            const preconditioner* prePreconditioner
        );


    // Destructor

        virtual ~preconditioner()
        {}


    // Member Functions

        //- Precondition a vector. Call this base class to apply
        // pre-preconditioner
        virtual void precondition
        (
            PtrList<volScalarField>& sVec,
            PtrList<volVectorField>& vVec
        ) const
        {
            if (prePreconditioner_)
            {
               prePreconditioner_->precondition(sVec, vVec);
            }
        }

};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#define makePreconditionerType(SS, nScalar, nVector)                           \
                                                                               \
typedef SS<nScalar, nVector> SS##nScalar##nVector;                             \
defineNamedTemplateTypeNameAndDebug(SS##nScalar##nVector, 0);                  \
                                                                               \
preconditioner<nScalar, nVector>::adddictionaryConstructorToTable<SS<nScalar, nVector>> \
    add##SS##nScalar##nVector##ConstructorToTable_;


#define makePreconditioner(SS)                                                 \
                                                                               \
makePreconditionerType(SS, 2, 1)

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#ifdef NoRepository
    #include "preconditionerNew.C"
#endif

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
