/*---------------------------------------------------------------------------*\

    HiSA: High Speed Aerodynamic solver

    Copyright (C) 2014-2015 Oliver Oxtoby - CSIR, South Africa
    Copyright (C) 2014-2015 Johan Heyns - CSIR, South Africa
    Copyright (C) 2011-2013 OpenFOAM Foundation

-------------------------------------------------------------------------------
License
    This file is part of HiSA.

    HiSA is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HiSA is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HiSA.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::pseudotimeControl

Description
    Convergence control class to supply convergence information/checks for
    the pseudotime iteration loop.

Authors
    Oliver Oxtoby
    Johan Heyns
        Council for Scientific and Industrial Research, South Africa

\*---------------------------------------------------------------------------*/

#ifndef pseudotimeControl_H
#define pseudotimeControl_H

#if FOUNDATION >= 6
#include "convergenceControl.H"
#include "singleRegionSolutionControl.H"
#else
#include "solutionControl.H"
#endif
#include "residualIO.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                        Class pseudotimeControl Declaration
\*---------------------------------------------------------------------------*/

class pseudotimeControl
:
#if FOUNDATION >= 6
    public singleRegionSolutionControl
#else
    public solutionControl
#endif
{
protected:

    // Protected data

        // Solution controls

#if FOUNDATION >= 6
            //- Current outer corrector
            label corr_;
#endif

            //- Steady state flag
            bool steadyState_;

            //- Maximum number of outer (pseudotime) correctors
            label nCorrOuter_;

            //- Minimum number of outer (pseudotime) correctors
            label nCorrOuterMin_;

            //- Flag to indicate whether to only solve turbulence on final iter
            bool turbOnFinalIterOnly_;

            //- Converged flag
            bool converged_;

            //- First iteration or first iteration after restart (no residual computed yet)
            bool firstIteration_;

        // Residuals

            residualIO residualTols_;
            residualIO residualTolsRel_;
            residualIO residuals_;
            residualIO initResiduals_;

            // For persistent storage of initial residuals
            IOdictionary state_;

    // Protected Member Functions

        //- Read controls from fvSolution dictionary
#if FOUNDATION >= 6 or OPENFOAM >= 1906
        virtual bool read();
#else
        virtual void read();
#endif

        //- Return true if all convergence checks are satisfied
        virtual bool criteriaSatisfied();

        //- Disallow default bitwise copy construct
        pseudotimeControl(const pseudotimeControl&);

        //- Disallow default bitwise assignment
        void operator=(const pseudotimeControl&);


public:


    // Static Data Members

        //- Run-time type information
        TypeName("pseudotimeControl");


    // Constructors

        //- Construct from mesh
        pseudotimeControl
        (
            fvMesh& mesh,
            const bool steadyState,
            const label nScalars,
            const label nVectors,
            const residualIO& defaultTol,
            const residualIO& defaultTolRel
        );


    //- Destructor
    virtual ~pseudotimeControl();


    // Member Functions

        // Access

            //- Maximum number of pseudotime correctors
            inline label nCorrOuter() const;


        // Solution control

            //- pseudotime loop
#if FOUNDATION >= 6
            bool loop();
#else
            virtual bool loop();
#endif

            //- Helper function to identify when to store the intial residuals
            inline bool storeInitialResiduals() const;

            //- Helper function to identify first outer (pseudotime) iteration
            inline bool firstIter() const;

            //- Helper function to identify final outer (pseudotime) iteration
            inline bool finalIter() const;

            //- Helper function to identify whether to solve for turbulence
            inline bool turbCorr() const;

            //- Helper function to store residual (initial solver residual)
            inline void setResidual(const residualIO& res);

            void setCorr(const label corr)
            {
                corr_ = corr;
            }

#if FOUNDATION >= 6
            label corr() const
            {
                return corr_;
            }
#endif
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#include "pseudotimeControlI.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
