#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
wclean findroot
wclean turbulenceModels
wclean incompressible
wclean compressible
wclean schemes
wcleanLnIncludeAll

#------------------------------------------------------------------------------
