#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmake libso pressureOutletNSCBC
wmake libso temperatureOutletNSCBC
wmake libso velocityOutletNSCBC
wmake libso velocityOutletNSCBCx
wmake libso velocityOutletNSCBCy
wmake libso velocityOutletNSCBCz
wmake libso waveTransmision

# ----------------------------------------------------------------- end-of-file
