#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean pressureOutletNSCBC
wclean temperatureOutletNSCBC
wclean velocityOutletNSCBC
wclean velocityOutletNSCBCx
wclean velocityOutletNSCBCy
wclean velocityOutletNSCBCz
wclean waveTransmision

# ----------------------------------------------------------------- end-of-file
