#!/bin/bash

#SBATCH --job-name=runFoam-V1.12
#SBATCH --partition=64c512g
#SBATCH -n 64
#SBATCH --ntasks-per-node=64
#SBATCH --output=%j.out
#SBATCH --error=%j.err

#1. Defining the container to be used
theRepo=/dssg/home/acct-medgm/medgm/00-sif
theContainerBaseName=openfoam
theVersion=v2006
theProvider=wjq
theImage=$theRepo/$theContainerBaseName-$theVersion-$theProvider.sif
 
#2. Project Name
project_name=03-hisa
foam_numberOfSubdomains=64

#2. Control parameter
theSolver=hisa
foam_MachInlet="1.05"     
foam_MacsOutlet="0.71"
foam_polyMesh_type="long"
foam_writeFormat="binary"
foam_fluxSchemes="AUSMPlusUp"

#2. Steady parameter
foam_steady_writeInterval="1"
foam_steady_maxCo="1.0e20"
foam_steady_endTime="1"
foam_steady_deltaT="1"
foam_steady_ddtScheme="steadyState"
foam_steady_writeControl="timeStep"
foam_steady_startFrom="startTime"
foam_steady_purgeWrite="0"
foam_steady_numberOfSubdomains=$foam_numberOfSubdomains
foam_steady_writeFormat=$foam_writeFormat
foam_steady_runTimeModifiable="false"
foam_steady_fluxSchemes=$foam_fluxSchemes
foam_steady_polyMesh_type=$foam_polyMesh_type
foam_steady_MachInlet=$foam_MachInlet
foam_steady_MacsOutlet=$foam_MacsOutlet


#2. Transient1 parameter
foam_transient1_writeInterval="0.5e-4"
foam_transient1_maxCo="50" 
foam_transient1_endTime="1" 
foam_transient1_deltaT="5.0e-7"
foam_transient1_ddtScheme="backward" 
foam_transient1_writeControl="adjustableRunTime"  
foam_transient1_runTimeModifiable="true"
foam_transient1_startFrom="latestTime"
foam_transient1_purgeWrite="0"
foam_transient1_numberOfSubdomains=$foam_numberOfSubdomains
foam_transient1_writeFormat=$foam_writeFormat
foam_transient1_fluxSchemes=$foam_fluxSchemes
foam_transient1_polyMesh_type=$foam_polyMesh_type
foam_transient1_MachInlet=$foam__MachInlet
foam_transient1_MacsOutlet=$foam__MacsOutlet

#2. Transient2 parameter
foam_transient2_writeInterval="0.5e-4"
foam_transient2_maxCo="1"
foam_transient2_endTime="0.1"
foam_transient2_deltaT="5.0e-8"
foam_transient2_ddtScheme="backward"
foam_transient2_writeControl="adjustableRunTime"
foam_transient2_runTimeModifiable="true"
foam_transient2_startFrom="latestTime"
foam_transient2_purgeWrite="0"
foam_transient2_numberOfSubdomains=$foam_numberOfSubdomains
foam_transient2_writeFormat=$foam_writeFormat
foam_transient2_fluxSchemes=$foam_fluxSchemes
foam_transient2_polyMesh_type=$foam_polyMesh_type
foam_transient2_MachInlet=$foam__MachInlet
foam_transient2_MacsOutlet=$foam__MacsOutlet



#2. Project Name
caseName=Ex2-$theSolver-$foam_MachInlet-$foam_MacsOutlet-$foam_fluxSchemes-$foam_steady_endTime-maxCo$foam_transient1_maxCo-$foam_transient1_deltaT-$foam_polyMesh_type
polyMeshName=polyMesh-igg-final-$foam_polyMesh_type


projectUserDir=$SLURM_SUBMIT_DIR/../../projectUserDir
baseWorkingDir=$SLURM_SUBMIT_DIR/../../run
caseDir=$baseWorkingDir/$caseName
logsDir=$caseDir/logs/pre



#4. Copy the file to run
mkdir -p $baseWorkingDir
#rm -rf $baseWorkingDir/$caseName
cp -rf $SLURM_SUBMIT_DIR/../../test_cases/$project_name  $caseDir

# create log directory
if ! [ -d $logsDir ]; then
   mkdir -p $logsDir
fi


#5. Defining OpenFOAM controlDict settings for Pawsey Best Practices
echo "----------> cd to $caseDir"
cd $caseDir
rm -rf *.err
rm -rf *.out
cp -rf constant/$polyMeshName constant/polyMesh
rm -rf constant/polyMesh-igg*
rm -rf constant/igg*

echo "----------> restore0Dir"
mv 0_org 0

#5. steday controlDict Setting
sed -i 's,^writeFormat.*,writeFormat    '"$foam_steady_writeFormat"';,' ./system/controlDict
sed -i 's,^runTimeModifiable.*,runTimeModifiable    '"$foam_steady_runTimeModifiable"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_steady_purgeWrite"';,' ./system/controlDict
sed -i 's,^startFrom.*,startFrom    '"$foam_steady_startFrom"';,' ./system/controlDict
sed -i 's,^deltaT.*,deltaT    '"$foam_steady_deltaT"';,' ./system/controlDict
sed -i 's,^writeInterval.*,writeInterval    '"$foam_steady_writeInterval"';,' ./system/controlDict
sed -i 's,^writeControl.*,writeControl    '"$foam_steady_writeControl"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_steady_purgeWrite"';,' ./system/controlDict
sed -i 's,^maxCo.*,maxCo    '"$foam_steady_maxCo"';,' ./system/controlDict
sed -i 's,^endTime.*,endTime    '"$foam_steady_endTime"';,' ./system/controlDict
sed -i 's,^numberOfSubdomains.*,numberOfSubdomains    '"$foam_steady_numberOfSubdomains"';,' ./system/decomposeParDict
sed -i 's,^Mach.*,Mach    '"$foam_steady_MachInlet"';,' ./0/include/freestreamConditions
sed -i 's,^Macs.*,Macs    '"$foam_steady_MacsOutlet"';,' ./0/include/freestreamConditions
sed -i 's,^fluxScheme.*,fluxScheme    '"$foam_steady_fluxSchemes"';,' ./system/fvSchemes
sed -i 's,backward,'"$foam_steady_ddtScheme"','  ./system/fvSchemes


echo "----------> Decompose"
singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage decomposePar -force 2>&1 | tee $logsDir/log.decomposePar2.$SLURM_JOBID

echo "----------> run the $theSolver"
srun --mpi=pmi2 singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage $theSolver -parallel 2>&1 | tee $logsDir/log.steadytheSolver.$SLURM_JOBID

echo "----------> FINISH STEADY STEP"

echo "----------> Reconstruct latest result"
singularity run -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage reconstructPar  2>&1 | tee $logsDir/log.reconstructPar.$SLURM_JOBID

rm -rf processors$foam_numberOfSubdomains
cp -rf 0/include $foam_steady_endTime
rm -rf 0
mv $foam_steady_endTime 0
rm -rf 0/uniform
sed -i '/location/d' 0/*



#5. Transient controlDict Setting
sed -i 's,^writeFormat.*,writeFormat    '"$foam_transient1_writeFormat"';,' ./system/controlDict
sed -i 's,^runTimeModifiable.*,runTimeModifiable    '"$foam_transient1_runTimeModifiable"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_transient1_purgeWrite"';,' ./system/controlDict
sed -i 's,^startFrom.*,startFrom    '"$foam_transient1_startFrom"';,' ./system/controlDict
sed -i 's,^deltaT.*,deltaT    '"$foam_transient1_deltaT"';,' ./system/controlDict
sed -i 's,^writeInterval.*,writeInterval    '"$foam_transient1_writeInterval"';,' ./system/controlDict
sed -i 's,^writeControl.*,writeControl    '"$foam_transient1_writeControl"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_transient1_purgeWrite"';,' ./system/controlDict
sed -i 's,^maxCo.*,maxCo    '"$foam_transient1_maxCo"';,' ./system/controlDict
sed -i 's,^endTime.*,endTime    '"$foam_transient1_endTime"';,' ./system/controlDict
sed -i 's,^numberOfSubdomains.*,numberOfSubdomains    '"$foam_transient1_numberOfSubdomains"';,' ./system/decomposeParDict
sed -i 's,^fluxScheme.*,fluxScheme    '"$foam_transient1_fluxSchemes"';,' ./system/fvSchemes
sed -i 's,steadyState,'"$foam_transient1_ddtScheme"','  ./system/fvSchemes


echo "----------> Decompose"
singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage decomposePar -force 2>&1 | tee $logsDir/log.decomposePar2.$SLURM_JOBID

echo "----------> run the transient1 $theSolver"
srun --mpi=pmi2 singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage $theSolver -parallel 2>&1 | tee $logsDir/log.trasient1theSolver.$SLURM_JOBID

echo "----------> FINISH TRANSIENT1 STEP"


echo "----------> Reconstruct latest result"
singularity run -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage reconstructPar -time 0:$foam_transient1_endTime 2>&1 | tee $logsDir/log.reconstructPar.$SLURM_JOBID

foam_transient2_startTime=$foam_transient1_endTime

cp -rf 0/include  $foam_transient2_startTime
line=18
insertHead='i\
#include        "include/freestreamConditions"
'
sed -i "$line$insertHead" $foam_transient2_startTime/T
sed -i "$line$insertHead" $foam_transient2_startTime/U
sed -i "$line$insertHead" $foam_transient2_startTime/p


echo "----------> Change to NRBC outlet boundary"
insertT='i\
        type            temperatureOutletNSCBC; \
        field           T; \
        gamma           1.4; \
        fieldInf        1; \
        lInf            0.07; \
        pInf            $poutlet; \
        etaAc           1; \
	value           uniform $Toutlet;
'


insertU='i\
        type            velocityOutletNSCBCx; \
        pInf            $poutlet; \
        gamma           1.4; \
        etaAc           1; \
        fieldInf        (1 0 0); \
        lInf            0.07; \
        value           uniform $Uoutlet;
'

insertp='i\
        type            pressureOutletNSCBC; \
        field           p; \
        gamma           1.4; \
        fieldInf        1; \
        lInf            0.07; \
        pInf            $poutlet; \
        etaAc           1;
'

function get_lineT() {
        sed -n -e '/OUTLET/=' $foam_transient2_startTime/T
}
function get_lineU() {
        sed -n -e '/OUTLET/=' $foam_transient2_startTime/U
}
function get_linep() {
        sed -n -e '/OUTLET/=' $foam_transient2_startTime/p
}

lineT=$(get_lineT)
lineT1=$((lineT +  2))  #for zeroGradient:2, charac:5
lineT2=$((lineT1 +  0))
lineU=$(get_lineU)
lineU1=$((lineU +  2))  #for zeroGradient:2, charac:5
lineU2=$((lineU1 +  0))
linep=$(get_linep)
linep1=$((linep +  2))
linep2=$((linep1 +  1))

insert_func() {
        sed -i "${lineT1},${lineT2}d" $foam_transient2_startTime/T
        sed -i "$lineT1$insertT" $foam_transient2_startTime/T
        sed -i "${lineU1},${lineU2}d" $foam_transient2_startTime/U
        sed -i "$lineU1$insertU" $foam_transient2_startTime/U
        sed -i "${linep1},${linep2}d" $foam_transient2_startTime/p
        sed -i "$linep1$insertp" $foam_transient2_startTime/p
}

insert_func



sed -i 's,^writeFormat.*,writeFormat    '"$foam_transient2_writeFormat"';,' ./system/controlDict
sed -i 's,^runTimeModifiable.*,runTimeModifiable    '"$foam_transient2_runTimeModifiable"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_transient2_purgeWrite"';,' ./system/controlDict
sed -i 's,^startFrom.*,startFrom    '"$foam_transient2_startFrom"';,' ./system/controlDict
sed -i 's,^deltaT.*,deltaT    '"$foam_transient2_deltaT"';,' ./system/controlDict
sed -i 's,^writeInterval.*,writeInterval    '"$foam_transient2_writeInterval"';,' ./system/controlDict
sed -i 's,^writeControl.*,writeControl    '"$foam_transient2_writeControl"';,' ./system/controlDict
sed -i 's,^purgeWrite.*,purgeWrite    '"$foam_transient2_purgeWrite"';,' ./system/controlDict
sed -i 's,^maxCo.*,maxCo    '"$foam_transient2_maxCo"';,' ./system/controlDict
sed -i 's,^endTime.*,endTime    '"$foam_transient2_endTime"';,' ./system/controlDict
sed -i 's,^numberOfSubdomains.*,numberOfSubdomains    '"$foam_transient2_numberOfSubdomains"';,' ./system/decomposeParDict
sed -i 's,^fluxScheme.*,fluxScheme    '"$foam_transient2_fluxSchemes"';,' ./system/fvSchemes
sed -i 's,steadyState,'"$foam_transient2_ddtScheme"','  ./system/fvSchemes
sed -i 's,dualTime rPseudoDeltaT,,' ./system/fvSchemes


echo "----------> Decompose"
singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage decomposePar -force -latestTime 2>&1 | tee $logsDir/log.decomposePar2.$SLURM_JOBID


echo "----------> run the transient2 $theSolver"
srun --mpi=pmi2 singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage $theSolver -parallel 2>&1 | tee $logsDir/log.trasient2theSolver.$SLURM_JOBID

echo "----------> Reconstruct latest result"
singularity run -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage reconstructPar -time $foam_transient1_endTime:$foam_transient2_endTime  2>&1 | tee $logsDir/log.reconstructPar.$SLURM_JOBID



echo "----------> PostProcessing xyz for paraview plot"
singularity run -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage postProcess -func writeCellCentres  2>&1 | tee $logsDir/log.postprocessing.$SLURM_JOBID

echo "----------> FINISH"
