/*---------------------------------------------------------------------------*\

    HiSA: High Speed Aerodynamic solver

    Copyright (C) 2014-2018 Oliver Oxtoby - CSIR, South Africa
    Copyright (C) 2014-2018 Johan Heyns - CSIR, South Africa

-------------------------------------------------------------------------------
License
    This file is part of HiSA.

    HiSA is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HiSA is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HiSA.  If not, see <http://www.gnu.org/licenses/>.

Class
    lusgs

Description
    LU-SGS preconditioning as per Luo, Baum, Lohner, JCP 146 664-690 (1998).

Authors
    Oliver Oxtoby
    Johan Heyns
        Council for Scientific and Industrial Research, South Africa

\*---------------------------------------------------------------------------*/

#ifndef lusgs_H
#define lusgs_H

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#include "preconditioner.H"
#include "jacobianMatrix.H"
#include "fvCFD.H"
#include "fvjMatrix.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                           Class lusgs Declaration
\*---------------------------------------------------------------------------*/

template <int nScalar, int nVector>
class lusgs
:
    public preconditioner<nScalar, nVector>
{

    protected:

        //- Protected data
            autoPtr<scalarField> rDiagCoeff_;

        //- Private member functions

            template <class Type1, class Type2>
            void forwardSweep
            (
                const label celli,
                GeometricField<Type1, fvPatchField, volMesh>& result,
                const fvjMatrix<typename outerProduct<Type1, Type2>::type>& matrix,
                const Type2& delta
            ) const;

            template <class Type1, class Type2>
            void reverseSweep
            (
                const label celli,
                GeometricField<Type1, fvPatchField, volMesh>& result,
                const fvjMatrix<typename outerProduct<Type1, Type2>::type>& matrix,
                const Type2& delta
            ) const;

            void divideByDiagonal
            (
                const label& celli,
                FixedList<scalar, nScalar>& dS,
                FixedList<vector, nVector>& dV,
                const PtrList<volScalarField>& sVec,
                const PtrList<volVectorField>& vVec
            ) const;

    public:
        //- Runtime type information
        TypeName("LUSGS");

        lusgs
        (
            const dictionary& dict,
            const jacobianMatrix<nScalar,nVector>& jacobian,
            const preconditioner<nScalar,nVector>* prePreconditioner
        );

        //- Precondition a vector
        virtual void precondition
        (
            PtrList<volScalarField>& sVec,
            PtrList<volVectorField>& vVec
        ) const;

};

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#ifdef NoRepository
#   include "lusgsTemplates.C"
#endif

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
