/*---------------------------------------------------------------------------*\

    HiSA: High Speed Aerodynamic solver

    Copyright (C) 2014-2018 Johan Heyns - CSIR, South Africa
    Copyright (C) 2014-2018 Oliver Oxtoby - CSIR, South Africa
    Copyright (C) 2021 Oliver Oxtoby

-------------------------------------------------------------------------------
License
    This file is part of HiSA.

    HiSA is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HiSA is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HiSA.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

const solidThermo& thermo = thermo_();

tmp<volScalarField> magKappa;
if (thermo.isotropic())
{
    magKappa = thermo.kappa();
}
else
{
    magKappa = mag(thermo.Kappa());
}

tmp<volScalarField> tcp = thermo.Cp();
const volScalarField& cp = tcp();

tmp<volScalarField> trho = thermo.rho();
const volScalarField& rho = trho();

scalar DiNum =
    solidRegionDiffNo
    (
        mesh_(),
        time_,
        rho*cp,
        magKappa()
    );
